from monkeyevents.abstract_agent_event import AbstractAgentEvent
from monkeyevents.agent_shutdown_event import AgentShutdownEvent
from monkeyevents.cpu_consumption_event import CPUConsumptionEvent
from monkeyevents.credentials_stolen_event import CredentialsStolenEvent
from monkeyevents.defacement_event import DefacementEvent
from monkeyevents.exploitation_event import ExploitationEvent
from monkeyevents.file_encryption_event import FileEncryptionEvent
from monkeyevents.fingerprinting_event import FingerprintingEvent
from monkeyevents.hostname_discovery_event import HostnameDiscoveryEvent
from monkeyevents.http_request_event import HTTPRequestEvent
from monkeyevents.i_agent_event_serializer import IAgentEventSerializer
from monkeyevents.os_discovery_event import OSDiscoveryEvent
from monkeyevents.password_restoration_event import PasswordRestorationEvent
from monkeyevents.ping_scan_event import PingScanEvent
from monkeyevents.propagation_event import PropagationEvent
from monkeyevents.pydantic_agent_event_serializer import PydanticAgentEventSerializer
from monkeyevents.ram_consumption_event import RAMConsumptionEvent
from monkeyevents.schema import TIMESTAMP_FIELD
from monkeyevents.tcp_scan_event import TCPScanEvent

AbstractAgentEvent.source
AbstractAgentEvent.target
AbstractAgentEvent.timestamp
AbstractAgentEvent.tags

AgentShutdownEvent

CPUConsumptionEvent.utilization
CPUConsumptionEvent.cpu_number

CredentialsStolenEvent.stolen_credentials

DefacementEvent.DefacementTarget.INTERNAL
DefacementEvent.DefacementTarget.EXTERNAL
DefacementEvent.defacement_target
DefacementEvent.description

ExploitationEvent.target
ExploitationEvent.success
ExploitationEvent.exploiter_name
ExploitationEvent.error_message

FileEncryptionEvent.model_config
FileEncryptionEvent.file_path
FileEncryptionEvent.success
FileEncryptionEvent.error_message
FileEncryptionEvent.dump_file_path
FileEncryptionEvent._file_path_to_pure_path
FileEncryptionEvent.cls

FingerprintingEvent.target
FingerprintingEvent.os
FingerprintingEvent.os_version
FingerprintingEvent.discovered_services

HostnameDiscoveryEvent.hostname

HTTPRequestEvent.method
HTTPRequestEvent.url

IAgentEventSerializer.serialize
IAgentEventSerializer.deserialize

OSDiscoveryEvent.os
OSDiscoveryEvent.version

PasswordRestorationEvent.target
PasswordRestorationEvent.success

PingScanEvent.target
PingScanEvent.response_received
PingScanEvent.os

PropagationEvent.target
PropagationEvent.success
PropagationEvent.exploiter_name
PropagationEvent.error_message

PydanticAgentEventSerializer.serialize
PydanticAgentEventSerializer.deserialize

RAMConsumptionEvent.utilization
RAMConsumptionEvent.bytes

TCPScanEvent.target
TCPScanEvent.ports

TIMESTAMP_FIELD
