from monkeyevents.abstract_agent_event import AbstractAgentEvent
from monkeyevents.agent_shutdown_event import AgentShutdownEvent
from monkeyevents.cpu_consumption_event import CPUConsumptionEvent
from monkeyevents.credentials_stolen_event import CredentialsStolenEvent
from monkeyevents.defacement_event import DefacementEvent
from monkeyevents.exploitation_event import ExploitationEvent
from monkeyevents.file_encryption_event import FileEncryptionEvent
from monkeyevents.fingerprinting_event import FingerprintingEvent
from monkeyevents.hostname_discovery_event import HostnameDiscoveryEvent
from monkeyevents.http_request_event import HTTPRequestEvent
from monkeyevents.i_agent_event_serializer import IAgentEventSerializer
from monkeyevents.os_discovery_event import OSDiscoveryEvent
from monkeyevents.password_restoration_event import PasswordRestorationEvent
from monkeyevents.ping_scan_event import PingScanEvent
from monkeyevents.propagation_event import PropagationEvent
from monkeyevents.pydantic_agent_event_serializer import PydanticAgentEventSerializer
from monkeyevents.ram_consumption_event import RAMConsumptionEvent
from monkeyevents.schema import TIMESTAMP_FIELD
from monkeyevents.tags.attack import (
    ACCOUNT_MANIPULATION_T1098_TAG,
    ACTIVE_SCANNING_T1595_TAG,
    ALTERNATE_AUTHENTICATION_MATERIAL_T1550_TAG,
    BRUTE_FORCE_T1110_TAG,
    COMMAND_AND_SCRIPTING_INTERPRETER_T1059_TAG,
    CREDENTIALS_FROM_PASSWORD_STORES_T1555_TAG,
    DATA_ENCRYPTED_FOR_IMPACT_T1486_TAG,
    DATA_FROM_LOCAL_SYSTEM_T1005_TAG,
    DEFACEMENT_T1491_TAG,
    EXPLOITATION_FOR_CLIENT_EXECUTION_T1203_TAG,
    EXPLOITATION_OF_REMOTE_SERVICES_T1210_TAG,
    EXTERNAL_DEFACEMENT_T1491_002_TAG,
    FILE_AND_DIRECTORY_PERMISSIONS_MODIFICATION_T1222_TAG,
    GATHER_VICTIM_HOST_INFORMATION_T1592_TAG,
    INGRESS_TOOL_TRANSFER_T1105_TAG,
    INTERNAL_DEFACEMENT_T1491_001_TAG,
    NETWORK_SHARE_DISCOVERY_T1135_TAG,
    OS_CREDENTIAL_DUMPING_T1003_TAG,
    REMOTE_SERVICES_T1021_TAG,
    RESOURCE_HIJACKING_T1496_TAG,
    SYSTEM_INFORMATION_DISCOVERY_T1082_TAG,
    SYSTEM_SERVICES_T1569_TAG,
    UNSECURED_CREDENTIALS_T1552_TAG,
)
from monkeyevents.tcp_scan_event import TCPScanEvent

AbstractAgentEvent.source
AbstractAgentEvent.target
AbstractAgentEvent.timestamp
AbstractAgentEvent.tags

AgentShutdownEvent

CPUConsumptionEvent.utilization
CPUConsumptionEvent.cpu_number

CredentialsStolenEvent.stolen_credentials

DefacementEvent.DefacementTarget.INTERNAL
DefacementEvent.DefacementTarget.EXTERNAL
DefacementEvent.defacement_target
DefacementEvent.description

ExploitationEvent.target
ExploitationEvent.success
ExploitationEvent.exploiter_name
ExploitationEvent.error_message

FileEncryptionEvent.model_config
FileEncryptionEvent.file_path
FileEncryptionEvent.success
FileEncryptionEvent.error_message
FileEncryptionEvent.dump_file_path
FileEncryptionEvent._file_path_to_pure_path
FileEncryptionEvent.cls

FingerprintingEvent.target
FingerprintingEvent.os
FingerprintingEvent.os_version
FingerprintingEvent.discovered_services

HostnameDiscoveryEvent.hostname

HTTPRequestEvent.method
HTTPRequestEvent.url

IAgentEventSerializer.serialize
IAgentEventSerializer.deserialize

OSDiscoveryEvent.os
OSDiscoveryEvent.version

PasswordRestorationEvent.target
PasswordRestorationEvent.success

PingScanEvent.target
PingScanEvent.response_received
PingScanEvent.os

PropagationEvent.target
PropagationEvent.success
PropagationEvent.exploiter_name
PropagationEvent.error_message

PydanticAgentEventSerializer.serialize
PydanticAgentEventSerializer.deserialize

RAMConsumptionEvent.utilization
RAMConsumptionEvent.bytes

TCPScanEvent.target
TCPScanEvent.ports

TIMESTAMP_FIELD
OS_CREDENTIAL_DUMPING_T1003_TAG
DATA_FROM_LOCAL_SYSTEM_T1005_TAG
REMOTE_SERVICES_T1021_TAG
COMMAND_AND_SCRIPTING_INTERPRETER_T1059_TAG
ACCOUNT_MANIPULATION_T1098_TAG
INGRESS_TOOL_TRANSFER_T1105_TAG
BRUTE_FORCE_T1110_TAG
NETWORK_SHARE_DISCOVERY_T1135_TAG
UNSECURED_CREDENTIALS_T1552_TAG
EXPLOITATION_FOR_CLIENT_EXECUTION_T1203_TAG
EXPLOITATION_OF_REMOTE_SERVICES_T1210_TAG
FILE_AND_DIRECTORY_PERMISSIONS_MODIFICATION_T1222_TAG
DATA_ENCRYPTED_FOR_IMPACT_T1486_TAG
SYSTEM_SERVICES_T1569_TAG
SYSTEM_INFORMATION_DISCOVERY_T1082_TAG
RESOURCE_HIJACKING_T1496_TAG
ALTERNATE_AUTHENTICATION_MATERIAL_T1550_TAG
CREDENTIALS_FROM_PASSWORD_STORES_T1555_TAG
GATHER_VICTIM_HOST_INFORMATION_T1592_TAG
ACTIVE_SCANNING_T1595_TAG
DEFACEMENT_T1491_TAG
INTERNAL_DEFACEMENT_T1491_001_TAG
EXTERNAL_DEFACEMENT_T1491_002_TAG
